### PR TITLE
Fix migration into individual package

### LINKED ISSUE #1203: Move models and table creation to individual packages
Currently all models and table creation code is in core. We need to move it to individual packages. 

Also, all database creation logic should be in migrations in individual commands.

### PR DESCRIPTION
**Pull request by sagarnasit**
Fixes #1203 

Depends on: 
https://github.com/EasyEngine/auth-command/pull/9

Move migration execution in individual packages. Change migration execution logic for package migratoin as well.

### CODE REVIEW

File: php/EE/Migration/Executor.php [hunk 1]
```diff
@@ -93,39 +118,45 @@ private static function execute_migration_stack( $migrations ) {
         }
     }
 
-    private static function get_migrations_to_execute() {
+    private static function get_migrations_to_execute( $path ) {
```
Comment (kirtangajjar) [inline php/EE/Migration/Executor.php]: Add doc comment in function

File: php/EE/Migration/Executor.php [hunk 2]
```diff
@@ -93,39 +118,45 @@ private static function execute_migration_stack( $migrations ) {
...
         return array_values(
             array_diff(
-                self::get_migrations_from_fs(),
+                self::get_migrations_from_fs( $path ),
                 self::get_migrations_from_db()
             )
         );
     }
 
     private static function get_migrations_from_db() {
```
Comment (kirtangajjar) [inline php/EE/Migration/Executor.php]: Add doc comment in function

File: php/EE/Migration/Executor.php [hunk 3]
```diff
@@ -93,39 +118,45 @@ private static function execute_migration_stack( $migrations ) {
...
-        return Migration::all();
+        return Migration::get_migrations();
     }
 
-    private static function get_migrations_from_fs() {
+    private static function get_migrations_from_fs( $path ) {
```
Comment (kirtangajjar) [inline php/EE/Migration/Executor.php]: Add doc comment in function

File: php/EE/Migration/Executor.php [hunk 4]
```diff
@@ -93,39 +118,45 @@ private static function execute_migration_stack( $migrations ) {
...
         array_walk( $migrations, function( &$migration, $index ) {
             $migration = rtrim( $migration, '.php' );
         });
         return $migrations;
     }
 
-    private static function get_migration_path( $migration_name ) {
-        return self::MIGRATION_PATH . $migration_name . '.php' ;
-    }
+	private static function get_migration_path( $migration_name ) {
```
Comment (kirtangajjar) [inline php/EE/Migration/Executor.php]: Add doc comment in function

File: php/EE/Migration/Executor.php [hunk 5]
```diff
@@ -93,39 +118,45 @@ private static function execute_migration_stack( $migrations ) {
...
+		preg_match( '/^\d*[_]([a-zA-Z-]*)[_]/', $migration_name, $matches );
+
+		if ( 'easyengine' === $matches[1] ) {
+			return EE_ROOT . "/migrations/$migration_name.php";
+		} else {
+			return EE_ROOT . "/vendor/easyengine/$matches[1]/migrations/$migration_name.php";
+		}
+	}
 
     private static function get_migration_class_name( $migration_name ) {
```
Comment (kirtangajjar) [inline php/EE/Migration/Executor.php]: Add doc comment in function

**Comment by kirtangajjar** [comment]
inform users that migrations are picked up from filesystem based on package name and inform where code is trying to find migration.  https://github.com/EasyEngine/easyengine/pull/1209/files#diff-bfc37b6395768a2f0ee3bc8a300c5fceR78

**Comment by kirtangajjar** [comment]
The PR is fine but we need to discuss how do we trigger migrations for the first time. Hence I'm blocking this PR for now.

**Comment by sagarnasit** [comment]
@kirtangajjar Please review this PR again as this is updated with latest migration changes from your PR.

File: php/EE/Migration/Executor.php [hunk 6]
```diff
@@ -14,13 +14,13 @@ class Executor {
...
 		Utils\delem_log( 'ee migration start' );
-		EE::log( 'Migrating EasyEngine data to new version' );
+		EE::debug( "Executing migrations" );
 
 		$migration_paths = self::get_migration_paths();
 
 		if ( empty( $migration_paths ) ) {
-			EE::success( 'Nothing to migrate' );
-			exit( 0 );
+			EE::debug( "Nothing to migrate" );
```
Comment (kirtangajjar) [inline php/EE/Migration/Executor.php]: Unless string interpolation is required, use single quotes. 

This should have been flagged by PHPCS ideally. If it has not on your machine, ping me tommorow, well set it up.

File: migrations/20180921123650_easyengine_test.php [hunk 7]
```diff
@@ -7,7 +7,7 @@
  *
  * @package EE\Migration
  */
-class Blank extends \EE\Migration\Base {
+class Test extends \EE\Migration\Base {
```
[the remark this answers is not in the document]
Comment (mbtamuli) [reply migrations/20180921123650_easyengine_test.php]: > we just need a directory with empty file in it(like .gitkeep).
`.gitkeep` will work for `git`, but the I don't think it will work for [Symphony Finder](https://symfony.com/doc/current/components/finder.html).

[the remark this answers is not in the document]
Comment (mbtamuli) [reply migrations/20180921123650_easyengine_test.php]: > we just need a directory with empty file in it(like .gitkeep).

`.gitkeep` will work for `git`, but the I don't think it will work for [Symphony Finder](https://symfony.com/doc/current/components/finder.html).

File: php/EE/Migration/Executor.php (hunk 6 above)
Comment (kirtangajjar) [reply php/EE/Migration/Executor.php]: Oh okay. I didn't fix those PHPCS errors intentionally #1124 since this PR of @sagarnasit was already there and I informed him to take care of fixes.

File: migrations/20180921123650_easyengine_test.php (hunk 7 above)
[the remark this answers is not in the document]
Comment (kirtangajjar) [reply migrations/20180921123650_easyengine_test.php]: We can intentionally add that file in first few releases of phar until we have first migration and after that we can remove that file.

Comment (kirtangajjar) [inline migrations/20180921123650_easyengine_test.php]: Remove this file
